version: '3'

services:
  tf:
    image: tensorflow/tensorflow:2.0.1-gpu-py3-jupyter

    # mount host system volume to save updates from container
    volumes:
      - jupyter:/tf/notebooks
    
    ports:
      - '8888:8888'
   
    # build:
    #   context: .
    #   dockerfile: Dockerfile


volumes:
  jupyter:



# version: "3.7"

# services:
#     gpu:
#         image: 'nvidia/cuda:9.0-base'
#         command: 'nvidia-smi'
#         device_requests:
#             - capabilities:
#                - "gpu"

#     tensorflow:
#         image: tensorflow/tensorflow:2.0.1-gpu-py3-jupyter
#         depends_on:
#             - gpu
#         ports:
#             - "8888:8888"

    # tf-gpu:
    #     image: tensorflow/tensorflow:2.0.1-gpu-py3-jupyter
    #     ports:
    #         - "8888:8888"
    #     build:
    #         context: .
    #         args:
    #             gpus: all
